[package]
name = "monkeyc-fmt"
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
description = "A syntax-preserving formatter for Garmin Monkey C"
license = "Unlicense"
repository = "https://github.com/DuckSoft/monkeyc-fmt"
readme = "README.md"
include = ["/src/**", "/tests/**", "/LICENSE", "/README.md"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pretty = "0.12"
tempfile = "3"
tree-sitter = "0.25"
tree-sitter-monkeyc = "0.1.1"
